[features]
seeds = false
skip-lint = false
[programs.localnet]
solly_bird_2 = "FDvzFQxR51WN1kBYf5KsU5SwMAhvEsPoncjh76SS3cD1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
